version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: deployment_assistant_postgres
    environment:
      POSTGRES_DB: deployment_assistant
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d deployment_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: deployment_assistant_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  # Optional: Database administration interface
  adminer:
    image: adminer:latest
    container_name: deployment_assistant_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: deployment_assistant_network



